version: '3'
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/moemoe89/practicing-grpc-client-golang
    container_name: golang_grpc_client
    restart: always
    ports:
      - "8794:8794"
    tty: true
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge