version: '3'
services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/moemoe89/go-grpc-client-ririk
    container_name: go_grpc_client_ririk
    restart: always
    ports:
      - "8794:8794"
    tty: true
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge